Added checks for file existence.

diff --git a/bin/MCRIBVolMask b/bin/MCRIBVolMask
--- a/bin/MCRIBVolMask
+++ b/bin/MCRIBVolMask
@@ -18,6 +18,11 @@ else
 	ASEGFILE=aseg.presurf
 fi
 
+if [ ! -f "${ASEGFILE}.mgz" ]
+then
+    echo "ASEG file not found: ${ASEGFILE}.mgz"
+    exit 1
+fi
 mris_volmask --aseg_name $ASEGFILE --label_left_white 2 --label_left_ribbon 3 --label_right_white 41 --label_right_ribbon 42  --save_ribbon $SUBJID
 
 if [ "$ASEGFILE" == "aseg.presurf.preunwmfix" ]
