Added T1 option for Deformable.

diff --git a/bin/MCRIBSurfReconDeformable b/bin/MCRIBSurfReconDeformable
--- a/bin/MCRIBSurfReconDeformable
+++ b/bin/MCRIBSurfReconDeformable
@@ -24,6 +24,20 @@ else
     USEFASTCOLLISION=
 fi
 
+if [ "$4" == "True" ]
+then
+    echo "Using T1"
+	if [ ! -f "RawT1RadiologicalIsotropic/$SUBJID.nii.gz"]
+	then
+	    echo "Use T1 was selected but RawT1RadiologicalIsotropic/$SUBJID.nii.gz was not found"
+		exit 1
+	fi
+	CONFIGFILE=`dirname $0`/../lib/Deformable/recon-neonatal-cortex-t1.cfg
+else
+    CONFIGFILE=`dirname $0`/../lib/Deformable/recon-neonatal-cortex.cfg
+fi
+
+
 OUTDIR=SurfReconDeformable
 
 mkdir -p $OUTDIR/$SUBJID/{temp,meshes,recon}
@@ -31,7 +45,8 @@ mkdir -p $OUTDIR/$SUBJID/{temp,meshes,recon}
 #export LD_LIBRARY_PATH=`dirname $0`/../MIRTK/MIRTK-install/lib:$LD_LIBRARY_PATH
 #export PATH=`dirname $0`/../MIRTK/MIRTK-install/bin:$PATH
 
-recon-neonatal-cortex -r `pwd` -c `dirname $0`/../lib/Deformable/recon-neonatal-cortex.cfg -s $SUBJID -t $OMP_NUM_THREADS -v -v -v -v -d -d -f -ensure-pial-is-outside-white-surface -j $J $USEFASTCOLLISION
+#echo recon-neonatal-cortex -r `pwd` -c $CONFIGFILE -s $SUBJID -t $OMP_NUM_THREADS -v -v -v -v -d -d -f -ensure-pial-is-outside-white-surface -j $J $USEFASTCOLLISION
+recon-neonatal-cortex -r `pwd` -c $CONFIGFILE -s $SUBJID -t $OMP_NUM_THREADS -v -v -v -v -d -d -f -ensure-pial-is-outside-white-surface -j $J $USEFASTCOLLISION 2>&1 | tee -a logs/$SUBJID.log
 
 #recon-neonatal-cortex  -r `pwd` -c `dirname $0`/../lib/Deformable/recon-neonatal-cortex.cfg -s $SUBJID -t 8 -v -d -d -f -ensure-pial-is-outside-white-surface -j $J
 #recon-neonatal-cortex -r `pwd` -c recon-neonatal-cortex.cfg -s $SUBJID -t 1 -v -d -f
